version: "3"

services:
  postgresql:
    image: postgres
    ports:
      - "54321:5432"
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  sonarqube:
    build:
      context: ./sonar
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: sq
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/postgres
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: root
